import streamlit as st
from sqlalchemy import text
import bcrypt
import logging
from datetime import date

def get_conn():
    return st.connection("mysql", type="sql")

    def init_db():
        conn = get_conn()
            with conn.session as s:
                    # Användare
                            s.execute(text("CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255) UNIQUE, password_hash VARCHAR(255))"))
                                    # Samling
                                            s.execute(text('''
                                                        CREATE TABLE IF NOT EXISTS collection (
                                                                        id INT AUTO_INCREMENT PRIMARY KEY,
                                                                                        user_id INT,
                                                                                                        api_id VARCHAR(100),
                                                                                                                        item_name VARCHAR(255),
                                                                                                                                        set_code VARCHAR(50),
                                                                                                                                                        card_number VARCHAR(50),
                                                                                                                                                                        variant VARCHAR(50) DEFAULT 'Normal',
                                                                                                                                                                                        card_condition VARCHAR(20) DEFAULT 'NM',
                                                                                                                                                                                                        quantity INT DEFAULT 1,
                                                                                                                                                                                                                        market_value DECIMAL(10, 2),
                                                                                                                                                                                                                                        purchase_price DECIMAL(10, 2),
                                                                                                                                                                                                                                                        image_url VARCHAR(500),
                                                                                                                                                                                                                                                                        is_graded BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                            '''))
                                                                                                                                                                                                                                                                                                                    # Historik
                                                                                                                                                                                                                                                                                                                            s.execute(text("CREATE TABLE IF NOT EXISTS portfolio_history (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT, recorded_date DATE, total_value DECIMAL(10, 2), UNIQUE KEY (user_id, recorded_date))"))
                                                                                                                                                                                                                                                                                                                                    s.commit()

                                                                                                                                                                                                                                                                                                                                    def verify_user(u, p):
                                                                                                                                                                                                                                                                                                                                        conn = get_conn()
                                                                                                                                                                                                                                                                                                                                            res = conn.query("SELECT id, password_hash FROM users WHERE username = :u", params={"u": u})
                                                                                                                                                                                                                                                                                                                                                if not res.empty and bcrypt.checkpw(p.encode(), res.iloc[0]['password_hash'].encode()):
                                                                                                                                                                                                                                                                                                                                                        return res.iloc[0]['id']
                                                                                                                                                                                                                                                                                                                                                            return None

                                                                                                                                                                                                                                                                                                                                                            def add_to_collection(uid, api_id, name, set_c, num, val, img, var="Normal", qty=1):
                                                                                                                                                                                                                                                                                                                                                                conn = get_conn()
                                                                                                                                                                                                                                                                                                                                                                    with conn.session as s:
                                                                                                                                                                                                                                                                                                                                                                            s.execute(text('''
                                                                                                                                                                                                                                                                                                                                                                                        INSERT INTO collection (user_id, api_id, item_name, set_code, card_number, market_value, image_url, variant, quantity)
                                                                                                                                                                                                                                                                                                                                                                                                    VALUES (:uid, :aid, :n, :s, :num, :v, :img, :var, :q)
                                                                                                                                                                                                                                                                                                                                                                                                                ON DUPLICATE KEY UPDATE quantity = quantity + :q
                                                                                                                                                                                                                                                                                                                                                                                                                        '''), {"uid": uid, "aid": api_id, "n": name, "s": set_c, "num": num, "v": val, "img": img, "var": var, "q": qty})
                                                                                                                                                                                                                                                                                                                                                                                                                                s.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                