import streamlit as st
import requests
from database import add_to_collection

st.title("Lägg till kort")

tab1, tab2 = st.tabs(["🔍 Sök (API)", "✏️ Manuell Inmatning"])

with tab1:
    search_term = st.text_input("Sök Pokémon-kort (ex. 'Charizard')", key="api_search")
        
            if st.button("Sök API", type="primary"):
                    if search_term.strip():
                                with st.spinner("Hämtar data..."):
                                                url = f"https://api.pokemontcg.io/v2/cards?q=name:\"{search_term}\"&pageSize=12"
                                                                res = requests.get(url)
                                                                                if res.status_code == 200:
                                                                                                    st.session_state.search_results = res.json().get("data", [])
                                                                                                                    else:
                                                                                                                                        st.error("Kunde inte nå API:et.")

                                                                                                                                            if st.session_state.get("search_results"):
                                                                                                                                                    st.divider()
                                                                                                                                                            cols = st.columns(3)
                                                                                                                                                                    for idx, card in enumerate(st.session_state.search_results):
                                                                                                                                                                                with cols[idx % 3]:
                                                                                                                                                                                                img_url = card.get("images", {}).get("small", "")
                                                                                                                                                                                                                name = card.get("name", "Okänd")
                                                                                                                                                                                                                                card_num = card.get("number", "")
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                # API:ets set.id är ofta nära URL-koden, men kan behöva justeras
                                                                                                                                                                                                                                                                                api_set_id = card.get("set", {}).get("id", "")
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                price = card.get("cardmarket", {}).get("prices", {}).get("averageSellPrice", 0.0)
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                if img_url:
                                                                                                                                                                                                                                                                                                                                                                    st.image(img_url, use_column_width=True)
                                                                                                                                                                                                                                                                                                                                                                                    st.markdown(f"**{name}** (#{card_num})")
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                    # Input för set-kod så du kan justera till den officiella logotyp-koden (ex me01)
                                                                                                                                                                                                                                                                                                                                                                                                                                    set_code_input = st.text_input("Set Kod (för officiell URL)", value=api_set_id, key=f"set_{card['id']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.write(f"Värde: {price} EUR")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if st.button("Lägg till", key=f"add_{card['id']}"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        add_to_collection(st.session_state.user_id, name, set_code_input, card_num, float(price), img_url)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.success("Tillagd!")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with tab2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with st.form("manual_add_form"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        man_name = st.text_input("Kortets namn")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                man_set_code = st.text_input("Set Kodnamn (ex. me01)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        man_card_num = st.text_input("Kortnummer (ex. 157)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                man_price = st.number_input("Marknadsvärde (EUR)", min_value=0.0, step=0.5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        man_img = st.text_input("Bild-URL (Frivilligt)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if st.form_submit_button("Spara manuellt", type="secondary"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if man_name.strip() and man_set_code.strip() and man_card_num.strip():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    add_to_collection(st.session_state.user_id, man_name, man_set_code, man_card_num, man_price, man_img)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.success("Sparat!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.error("Namn, Set Kod och Kortnummer krävs.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                